// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/oauth-client-service/proto/verify/verify.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_service_oauthclient_verify is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/oauth-client-service/proto/verify/verify.proto

It has these top-level messages:
	Request
	Response
*/
package com_HailoOSS_service_oauthclient_verify

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request struct {
	Token            *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	Provider         *string `protobuf:"bytes,2,req,name=provider" json:"provider,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *Request) GetProvider() string {
	if m != nil && m.Provider != nil {
		return *m.Provider
	}
	return ""
}

type Response struct {
	Valid            *bool  `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetValid() bool {
	if m != nil && m.Valid != nil {
		return *m.Valid
	}
	return false
}

func init() {
}
