// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/oauth-client-service/proto/info/info.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_service_oauthclient_info is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/oauth-client-service/proto/info/info.proto

It has these top-level messages:
	Request
	Response
*/
package com_HailoOSS_service_oauthclient_info

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request struct {
	Token            *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	Provider         *string `protobuf:"bytes,2,req,name=provider" json:"provider,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *Request) GetProvider() string {
	if m != nil && m.Provider != nil {
		return *m.Provider
	}
	return ""
}

type Response struct {
	Email            *string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	GivenName        *string `protobuf:"bytes,2,opt,name=givenName" json:"givenName,omitempty"`
	FamilyName       *string `protobuf:"bytes,3,opt,name=familyName" json:"familyName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *Response) GetGivenName() string {
	if m != nil && m.GivenName != nil {
		return *m.GivenName
	}
	return ""
}

func (m *Response) GetFamilyName() string {
	if m != nil && m.FamilyName != nil {
		return *m.FamilyName
	}
	return ""
}

func init() {
}
