// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/oauth-client-service/proto/provider.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_service_oauthclient_provider is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/oauth-client-service/proto/provider.proto

It has these top-level messages:
*/
package com_HailoOSS_service_oauthclient_provider

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type OauthProvider int32

const (
	OauthProvider_GOOGLE   OauthProvider = 0
	OauthProvider_FACEBOOK OauthProvider = 1
)

var OauthProvider_name = map[int32]string{
	0: "GOOGLE",
	1: "FACEBOOK",
}
var OauthProvider_value = map[string]int32{
	"GOOGLE":   0,
	"FACEBOOK": 1,
}

func (x OauthProvider) Enum() *OauthProvider {
	p := new(OauthProvider)
	*p = x
	return p
}
func (x OauthProvider) String() string {
	return proto.EnumName(OauthProvider_name, int32(x))
}
func (x OauthProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *OauthProvider) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OauthProvider_value, data, "OauthProvider")
	if err != nil {
		return err
	}
	*x = OauthProvider(value)
	return nil
}

func init() {
	proto.RegisterEnum("com.HailoOSS.service.oauthclient.provider.OauthProvider", OauthProvider_name, OauthProvider_value)
}
